theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# theme: jekyll-theme-minimal
title: "Mohammad Tavakolian"
description: This is my personal website, where I share the recent events and news about my research career.
logo: "/images/logo.png"
