theme: jekyll-theme-minimal
title: "Mohammad Tavakolian"
description: This is my personal website, where I share the recent events and news about my research career.
logo: "/images/logo.png"
email: "mohammad.tavakolian@oulu.fi"
  
